local opt = vim.opt

opt.wildignore = "__pycache__"
opt.wildignore = opt.wildignore + { "*.o", "*~", "*.pyc", "*pycache*" }
opt.pumblend = 17
opt.wildmode = "longest:full"
opt.wildoptions = "pum"
opt.showcmd = true
opt.cmdheight = 1 
opt.incsearch = true 
opt.showmatch = true 
opt.relativenumber = true 
opt.number = true 

opt.termguicolors = true
opt.hidden = true 
opt.splitright = true 
opt.splitbelow = true 
opt.updatetime = 100 
opt.hlsearch = true 
opt.scrolloff = 8 
opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.expandtab = true
opt.belloff = "all" 
opt.clipboard = "unnamedplus"
opt.mouse = "a"
opt.joinspaces = false 
